<hr />
<div class="error">
	<h3>ERROR: FORBIDDEN</h3>
	<pre> 
Contact service => <?php  print $autosite['servicenr'] ?>
   </pre>
<div align='center'>
<img border='0' src="<?php print $autosite['layout']?>toegang3.gif" align='left'width="100" height="100" />
<img border='0' src="<?php print $autosite['layout']?>toegang2.gif" align='left'width="100" height="100" />
<img border='0' src="<?php print $autosite['layout']?>toegang1.gif" align='left'width="100" height="100" />
<img border='0' src="<?php print $autosite['layout']?>toegang4.gif" align='left'width="100" height="100" />
</div>
<img border='1' src="<?php print $autosite['layout']?>toegang.gif" align='left'/>

