<div class="editorbtn left" onclick="javascript:doWYSIWYG('justifyleft')" id="left"></div> 
<div class="editorbtn center" onclick="javascript:doWYSIWYG('justifycenter')" id="center"></div>
<div class="editorbtn right" onclick="javascript:doWYSIWYG('justifyright')" id="right"></div>
<div class="editorbtn fore" onclick="javascript:doWYSIWYG('');" id="fore"></div> 
<div class="editorbtn back" onclick="javascript:doWYSIWYG('')" id="back"></div>
<div class="editorbtn bold" onclick="javascript:doWYSIWYG('bold')" id="bold">bold</div> 