<!--backcolor,bold,contentReadOnly,copy,createbookmark,createlink,cut,decreasefontsize,delete,fontname,fontsize,forecolor,formatblock,heading,hilitecolor,increasefontsize,indent,inserthorizontalrule,inserthtml,insertimage,insertorderedlist,insertunorderedlist,insertparagraph,italic,justifycenter,justifyfull,justifyleft,justifyright,multipleselection,outdent,overwrite,paste,print,redo,refresh,removeformat,saveas,selectall,strikethrough,styleWithCSS,subscript,superscript,unbookmark,underline,undo,unlink-->

<a class="editorbtn open"		href="javascript:setvisible('open')" 				id="load" >open</a>
<a class="editorbtn save"		href="javascript:setvisible('tosave')" 				id="save">save</a> 
<a class="editorbtn cut"		href="javascript:doWYSIWYG('cut')" 				id="cut">cut</a> 
<a class="editorbtn copy"		href="javascript:doWYSIWYG('copy')" 				id="copy">copy</a> 
<a class="editorbtn paste"		href="javascript:doWYSIWYG('paste')" 				id="paste">paste</a> 
<a class="editorbtn bold"           href="javascript:doWYSIWYG('Bold');" 				id="bold">bold</a> 
<a class="editorbtn underline" 	    href="javascript:doWYSIWYG('underline')" 			id="underline">underl</a> 
<a class="editorbtn strike" 	   href="javascript:doWYSIWYG('strikethrough')"            id="strike">strike</a>
<a class="editorbtn removeFormat"   href="javascript:doWYSIWYG('removeformat')"             id="removeFormat">del css</a>
<a class="editorbtn ileft" 		href="javascript:doWYSIWYG('Outdent')" 				id="ileft">indentL</a> 
<a class="editorbtn iright" 	   href="javascript:doWYSIWYG('Indent')" 				id="iright">indentR</a> 
<a class="editorbtn rule" 		href="javascript:doWYSIWYG('inserthorizontalrule')"  id="rule">rule</a> 
<a class="editorbtn bullets" 	  href="javascript:doWYSIWYG('insertunorderedlist')"  id="bullets">bullets</a> 
<a class="editorbtn ordlist" 	  href="javascript:doWYSIWYG('insertorderedlist')" 	id="ordlist">list</a>
<a class="editorbtn form" 		href="javascript:setvisible('forms')" 				id="form">form</a> 
<a class="editorbtn symbol" 	   href="javascript:setvisible('charmap')" 				id="symbol">symbool</a> 
<a class="editorbtn image" 		href="javascript:doWYSIWYG('InsertImage', true)" 	id="image">image</a> 
<a class="editorbtn flash" 		href="javascript:setvisible('flashPop')" 			id="flash">flash</a> 
<a class="editorbtn addHTML"	   href="javascript:setvisible('htmlQuickTagPop')" 		id="addHTML">addHTML</a>
<a class="editorbtn table" 		href="javascript:setvisible('tables')" 				id="table">table</a>